sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - rbx-2
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
notifications:
  email:
    - tj+travis_zassets_plugins_ember_emblem@a13.fr
